env:
    ghtoken: "ENCRYPTED[!312c4965ff6b7f37ae5e0178b0ef8a76eefe143491126d843f54a6b63d8dfde60da2105275bfb2ff420924785a302234!]"
    lunch: lunch derp_earth-userdebug
    make: goafterlife earth

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: cimg/deploy:2025.01
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "XeroMz69"
       - git config --global user.email "adamyd18@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - mkdir -p ~/ccache

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - sudo apt install git-lfs
      - mkdir -p ~/derp
      - cd ~/derp
      - git lfs install
      - repo init --depth=1 -u https://github.com/XeroMz69/android_manifest.git -b 14 --git-lfs
      - git-lfs install
      - git clone https://github.com/XeroMz69/manifest-lokal.git -b derpfest .repo/local_manifests
      - repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
      - rm -rf vendor/xiaomi
      - git clone https://github.com/mt6768-dev/proprietary_vendor_xiaomi_earth.git $WORKDIR/vendor/xiaomi/earth --depth 1
      - git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b $WORKDIR/prebuilts/prebuilts/clang/host/linux-x86/clang-los --depth 1
      
  Build_script:
      - export BUILD_USERNAME="xero"
      - export BUILD_HOSTNAME="urmom"
      - export KBUILD_BUILD_USER="xero"
      - export KBUILD_BUILD_HOST="urmom" 
      - export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
      - export TZ=Asia/Jakarta
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
#      - ./collect.sh
      - ./final.sh
 #     - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      
